
package oralce.offical.javaee.web.services.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://services.web.javaee.offical.oralce/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://services.web.javaee.offical.oralce/", className = "com.demo.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://services.web.javaee.offical.oralce/", className = "com.demo.client.SayHelloResponse")
    @Action(input = "http://services.web.javaee.offical.oralce/Hello/sayHelloRequest", output = "http://services.web.javaee.offical.oralce/Hello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
