//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "binName" , "binItemCount" , "binParameter"
})
@XmlRootElement(name = "Bin")
public class Bin {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "name" , "value"
    })
    public static class BinParameter {

        @XmlElement(name = "Name" , required = true)
        protected String name;
        @XmlElement(name = "Value" , required = true)
        protected String value;

        
        public String getName() {
            return this.name;
        }

        
        public String getValue() {
            return this.value;
        }

        
        public void setName(String value) {
            this.name = value;
        }

        
        public void setValue(String value) {
            this.value = value;
        }

    }

    @XmlElement(name = "BinItemCount" , required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger binItemCount;
    @XmlElement(name = "BinName" , required = true)
    protected String binName;

    @XmlElement(name = "BinParameter")
    protected List<Bin.BinParameter> binParameter;

    
    public BigInteger getBinItemCount() {
        return this.binItemCount;
    }

    
    public String getBinName() {
        return this.binName;
    }

    
    public List<Bin.BinParameter> getBinParameter() {
        if (this.binParameter == null) this.binParameter = new ArrayList<Bin.BinParameter>();
        return this.binParameter;
    }

    
    public void setBinItemCount(BigInteger value) {
        this.binItemCount = value;
    }

    
    public void setBinName(String value) {
        this.binName = value;
    }

}
