//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "request" , "browseNode"
})
@XmlRootElement(name = "BrowseNodes")
public class BrowseNodes {

    @XmlElement(name = "BrowseNode")
    protected List<BrowseNode> browseNode;
    @XmlElement(name = "Request")
    protected Request request;

    
    public List<BrowseNode> getBrowseNode() {
        if (this.browseNode == null) this.browseNode = new ArrayList<BrowseNode>();
        return this.browseNode;
    }

    
    public Request getRequest() {
        return this.request;
    }

    
    public void setRequest(Request value) {
        this.request = value;
    }

}
