//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BrowseNodeLookupRequest" , propOrder = {
    "browseNodeId" , "responseGroup"
})
public class BrowseNodeLookupRequest {

    @XmlElement(name = "BrowseNodeId")
    protected List<String> browseNodeId;
    @XmlElement(name = "ResponseGroup")
    protected List<String> responseGroup;

    
    public List<String> getBrowseNodeId() {
        if (this.browseNodeId == null) this.browseNodeId = new ArrayList<String>();
        return this.browseNodeId;
    }

    
    public List<String> getResponseGroup() {
        if (this.responseGroup == null) this.responseGroup = new ArrayList<String>();
        return this.responseGroup;
    }

}
