//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "request" , "cartId" , "hmac" , "urlEncodedHMAC" , "purchaseURL" , "mobileCartURL" , "subTotal" , "cartItems" ,
    "savedForLaterItems" , "similarProducts" , "topSellers" , "newReleases" , "similarViewedProducts" ,
    "otherCategoriesSimilarProducts"
})
@XmlRootElement(name = "Cart")
public class Cart {

    @XmlElement(name = "CartId" , required = true)
    protected String cartId;
    @XmlElement(name = "CartItems")
    protected CartItems cartItems;
    @XmlElement(name = "HMAC" , required = true)
    protected String hmac;
    @XmlElement(name = "MobileCartURL")
    protected String mobileCartURL;
    @XmlElement(name = "NewReleases")
    protected NewReleases newReleases;
    @XmlElement(name = "OtherCategoriesSimilarProducts")
    protected OtherCategoriesSimilarProducts otherCategoriesSimilarProducts;
    @XmlElement(name = "PurchaseURL")
    protected String purchaseURL;
    @XmlElement(name = "Request")
    protected Request request;
    @XmlElement(name = "SavedForLaterItems")
    protected SavedForLaterItems savedForLaterItems;
    @XmlElement(name = "SimilarProducts")
    protected SimilarProducts similarProducts;
    @XmlElement(name = "SimilarViewedProducts")
    protected SimilarViewedProducts similarViewedProducts;
    @XmlElement(name = "SubTotal")
    protected Price subTotal;
    @XmlElement(name = "TopSellers")
    protected TopSellers topSellers;
    @XmlElement(name = "URLEncodedHMAC" , required = true)
    protected String urlEncodedHMAC;

    
    public String getCartId() {
        return this.cartId;
    }

    
    public CartItems getCartItems() {
        return this.cartItems;
    }

    
    public String getHMAC() {
        return this.hmac;
    }

    
    public String getMobileCartURL() {
        return this.mobileCartURL;
    }

    
    public NewReleases getNewReleases() {
        return this.newReleases;
    }

    
    public OtherCategoriesSimilarProducts getOtherCategoriesSimilarProducts() {
        return this.otherCategoriesSimilarProducts;
    }

    
    public String getPurchaseURL() {
        return this.purchaseURL;
    }

    
    public Request getRequest() {
        return this.request;
    }

    
    public SavedForLaterItems getSavedForLaterItems() {
        return this.savedForLaterItems;
    }

    
    public SimilarProducts getSimilarProducts() {
        return this.similarProducts;
    }

    
    public SimilarViewedProducts getSimilarViewedProducts() {
        return this.similarViewedProducts;
    }

    
    public Price getSubTotal() {
        return this.subTotal;
    }

    
    public TopSellers getTopSellers() {
        return this.topSellers;
    }

    
    public String getURLEncodedHMAC() {
        return this.urlEncodedHMAC;
    }

    
    public void setCartId(String value) {
        this.cartId = value;
    }

    
    public void setCartItems(CartItems value) {
        this.cartItems = value;
    }

    
    public void setHMAC(String value) {
        this.hmac = value;
    }

    
    public void setMobileCartURL(String value) {
        this.mobileCartURL = value;
    }

    
    public void setNewReleases(NewReleases value) {
        this.newReleases = value;
    }

    
    public void setOtherCategoriesSimilarProducts(OtherCategoriesSimilarProducts value) {
        this.otherCategoriesSimilarProducts = value;
    }

    
    public void setPurchaseURL(String value) {
        this.purchaseURL = value;
    }

    
    public void setRequest(Request value) {
        this.request = value;
    }

    
    public void setSavedForLaterItems(SavedForLaterItems value) {
        this.savedForLaterItems = value;
    }

    
    public void setSimilarProducts(SimilarProducts value) {
        this.similarProducts = value;
    }

    
    public void setSimilarViewedProducts(SimilarViewedProducts value) {
        this.similarViewedProducts = value;
    }

    
    public void setSubTotal(Price value) {
        this.subTotal = value;
    }

    
    public void setTopSellers(TopSellers value) {
        this.topSellers = value;
    }

    
    public void setURLEncodedHMAC(String value) {
        this.urlEncodedHMAC = value;
    }

}
