//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CartCreateRequest" , propOrder = {
    "mergeCart" , "items" , "responseGroup"
})
public class CartCreateRequest {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "item"
    })
    public static class Items {

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "" , propOrder = {
            "asin" , "offerListingId" , "quantity" , "associateTag" , "listItemId" , "metaData"
        })
        public static class Item {

            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "" , propOrder = {
                "key" , "value"
            })
            public static class MetaData {

                @XmlElement(name = "Key")
                protected String key;
                @XmlElement(name = "Value")
                protected String value;

                
                public String getKey() {
                    return this.key;
                }

                
                public String getValue() {
                    return this.value;
                }

                
                public void setKey(String value) {
                    this.key = value;
                }

                
                public void setValue(String value) {
                    this.value = value;
                }

            }

            @XmlElement(name = "ASIN")
            protected String asin;
            @XmlElement(name = "AssociateTag")
            protected String associateTag;
            @XmlElement(name = "ListItemId")
            protected String listItemId;
            @XmlElement(name = "MetaData")
            protected List<CartCreateRequest.Items.Item.MetaData> metaData;
            @XmlElement(name = "OfferListingId")
            protected String offerListingId;

            @XmlElement(name = "Quantity")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger quantity;

            
            public String getASIN() {
                return this.asin;
            }

            
            public String getAssociateTag() {
                return this.associateTag;
            }

            
            public String getListItemId() {
                return this.listItemId;
            }

            
            public List<CartCreateRequest.Items.Item.MetaData> getMetaData() {
                if (this.metaData == null) this.metaData = new ArrayList<CartCreateRequest.Items.Item.MetaData>();
                return this.metaData;
            }

            
            public String getOfferListingId() {
                return this.offerListingId;
            }

            
            public BigInteger getQuantity() {
                return this.quantity;
            }

            
            public void setASIN(String value) {
                this.asin = value;
            }

            
            public void setAssociateTag(String value) {
                this.associateTag = value;
            }

            
            public void setListItemId(String value) {
                this.listItemId = value;
            }

            
            public void setOfferListingId(String value) {
                this.offerListingId = value;
            }

            
            public void setQuantity(BigInteger value) {
                this.quantity = value;
            }

        }

        @XmlElement(name = "Item")
        protected List<CartCreateRequest.Items.Item> item;

        
        public List<CartCreateRequest.Items.Item> getItem() {
            if (this.item == null) this.item = new ArrayList<CartCreateRequest.Items.Item>();
            return this.item;
        }

    }

    @XmlElement(name = "Items")
    protected CartCreateRequest.Items items;
    @XmlElement(name = "MergeCart")
    protected String mergeCart;

    @XmlElement(name = "ResponseGroup")
    protected List<String> responseGroup;

    
    public CartCreateRequest.Items getItems() {
        return this.items;
    }

    
    public String getMergeCart() {
        return this.mergeCart;
    }

    
    public List<String> getResponseGroup() {
        if (this.responseGroup == null) this.responseGroup = new ArrayList<String>();
        return this.responseGroup;
    }

    
    public void setItems(CartCreateRequest.Items value) {
        this.items = value;
    }

    
    public void setMergeCart(String value) {
        this.mergeCart = value;
    }

}
