//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CartItem" , propOrder = {
    "cartItemId" , "asin" , "sellerNickname" , "quantity" , "title" , "productGroup" , "metaData" , "price" ,
    "itemTotal"
})
public class CartItem {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "keyValuePair"
    })
    public static class MetaData {

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "" , propOrder = {
            "key" , "value"
        })
        public static class KeyValuePair {

            @XmlElement(name = "Key" , required = true)
            protected String key;
            @XmlElement(name = "Value" , required = true)
            protected String value;

            
            public String getKey() {
                return this.key;
            }

            
            public String getValue() {
                return this.value;
            }

            
            public void setKey(String value) {
                this.key = value;
            }

            
            public void setValue(String value) {
                this.value = value;
            }

        }

        @XmlElement(name = "KeyValuePair")
        protected List<CartItem.MetaData.KeyValuePair> keyValuePair;

        
        public List<CartItem.MetaData.KeyValuePair> getKeyValuePair() {
            if (this.keyValuePair == null) this.keyValuePair = new ArrayList<CartItem.MetaData.KeyValuePair>();
            return this.keyValuePair;
        }

    }

    @XmlElement(name = "ASIN")
    protected String asin;
    @XmlElement(name = "CartItemId" , required = true)
    protected String cartItemId;
    @XmlElement(name = "ItemTotal")
    protected Price itemTotal;
    @XmlElement(name = "MetaData")
    protected CartItem.MetaData metaData;
    @XmlElement(name = "Price")
    protected Price price;
    @XmlElement(name = "ProductGroup")
    protected String productGroup;
    @XmlElement(name = "Quantity" , required = true)
    protected String quantity;
    @XmlElement(name = "SellerNickname")
    protected String sellerNickname;

    @XmlElement(name = "Title")
    protected String title;

    
    public String getASIN() {
        return this.asin;
    }

    
    public String getCartItemId() {
        return this.cartItemId;
    }

    
    public Price getItemTotal() {
        return this.itemTotal;
    }

    
    public CartItem.MetaData getMetaData() {
        return this.metaData;
    }

    
    public Price getPrice() {
        return this.price;
    }

    
    public String getProductGroup() {
        return this.productGroup;
    }

    
    public String getQuantity() {
        return this.quantity;
    }

    
    public String getSellerNickname() {
        return this.sellerNickname;
    }

    
    public String getTitle() {
        return this.title;
    }

    
    public void setASIN(String value) {
        this.asin = value;
    }

    
    public void setCartItemId(String value) {
        this.cartItemId = value;
    }

    
    public void setItemTotal(Price value) {
        this.itemTotal = value;
    }

    
    public void setMetaData(CartItem.MetaData value) {
        this.metaData = value;
    }

    
    public void setPrice(Price value) {
        this.price = value;
    }

    
    public void setProductGroup(String value) {
        this.productGroup = value;
    }

    
    public void setQuantity(String value) {
        this.quantity = value;
    }

    
    public void setSellerNickname(String value) {
        this.sellerNickname = value;
    }

    
    public void setTitle(String value) {
        this.title = value;
    }

}
