//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CartGetRequest" , propOrder = {
    "cartId" , "hmac" , "mergeCart" , "responseGroup"
})
public class CartGetRequest {

    @XmlElement(name = "CartId")
    protected String cartId;
    @XmlElement(name = "HMAC")
    protected String hmac;
    @XmlElement(name = "MergeCart")
    protected String mergeCart;
    @XmlElement(name = "ResponseGroup")
    protected List<String> responseGroup;

    
    public String getCartId() {
        return this.cartId;
    }

    
    public String getHMAC() {
        return this.hmac;
    }

    
    public String getMergeCart() {
        return this.mergeCart;
    }

    
    public List<String> getResponseGroup() {
        if (this.responseGroup == null) this.responseGroup = new ArrayList<String>();
        return this.responseGroup;
    }

    
    public void setCartId(String value) {
        this.cartId = value;
    }

    
    public void setHMAC(String value) {
        this.hmac = value;
    }

    
    public void setMergeCart(String value) {
        this.mergeCart = value;
    }

}
