//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "collection"
})
@XmlRootElement(name = "Collections")
public class Collections {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "collectionSummary" , "collectionParent" , "collectionItem"
    })
    public static class Collection {

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "" , propOrder = {
            "asin" , "title"
        })
        public static class CollectionItem {

            @XmlElement(name = "ASIN")
            protected String asin;
            @XmlElement(name = "Title")
            protected String title;

            
            public String getASIN() {
                return this.asin;
            }

            
            public String getTitle() {
                return this.title;
            }

            
            public void setASIN(String value) {
                this.asin = value;
            }

            
            public void setTitle(String value) {
                this.title = value;
            }

        }

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "" , propOrder = {
            "asin" , "title"
        })
        public static class CollectionParent {

            @XmlElement(name = "ASIN")
            protected String asin;
            @XmlElement(name = "Title")
            protected String title;

            
            public String getASIN() {
                return this.asin;
            }

            
            public String getTitle() {
                return this.title;
            }

            
            public void setASIN(String value) {
                this.asin = value;
            }

            
            public void setTitle(String value) {
                this.title = value;
            }

        }

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "" , propOrder = {
            "lowestListPrice" , "highestListPrice" , "lowestSalePrice" , "highestSalePrice"
        })
        public static class CollectionSummary {

            @XmlElement(name = "HighestListPrice")
            protected Price highestListPrice;
            @XmlElement(name = "HighestSalePrice")
            protected Price highestSalePrice;
            @XmlElement(name = "LowestListPrice")
            protected Price lowestListPrice;
            @XmlElement(name = "LowestSalePrice")
            protected Price lowestSalePrice;

            
            public Price getHighestListPrice() {
                return this.highestListPrice;
            }

            
            public Price getHighestSalePrice() {
                return this.highestSalePrice;
            }

            
            public Price getLowestListPrice() {
                return this.lowestListPrice;
            }

            
            public Price getLowestSalePrice() {
                return this.lowestSalePrice;
            }

            
            public void setHighestListPrice(Price value) {
                this.highestListPrice = value;
            }

            
            public void setHighestSalePrice(Price value) {
                this.highestSalePrice = value;
            }

            
            public void setLowestListPrice(Price value) {
                this.lowestListPrice = value;
            }

            
            public void setLowestSalePrice(Price value) {
                this.lowestSalePrice = value;
            }

        }

        @XmlElement(name = "CollectionItem")
        protected List<Collections.Collection.CollectionItem> collectionItem;

        @XmlElement(name = "CollectionParent")
        protected Collections.Collection.CollectionParent collectionParent;

        @XmlElement(name = "CollectionSummary")
        protected Collections.Collection.CollectionSummary collectionSummary;

        
        public List<Collections.Collection.CollectionItem> getCollectionItem() {
            if (this.collectionItem == null) this.collectionItem =
                new ArrayList<Collections.Collection.CollectionItem>();
            return this.collectionItem;
        }

        
        public Collections.Collection.CollectionParent getCollectionParent() {
            return this.collectionParent;
        }

        
        public Collections.Collection.CollectionSummary getCollectionSummary() {
            return this.collectionSummary;
        }

        
        public void setCollectionParent(Collections.Collection.CollectionParent value) {
            this.collectionParent = value;
        }

        
        public void setCollectionSummary(Collections.Collection.CollectionSummary value) {
            this.collectionSummary = value;
        }

    }

    @XmlElement(name = "Collection")
    protected List<Collections.Collection> collection;

    
    public List<Collections.Collection> getCollection() {
        if (this.collection == null) this.collection = new ArrayList<Collections.Collection>();
        return this.collection;
    }

}
