//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "keywords" , "message"
})
@XmlRootElement(name = "CorrectedQuery")
public class CorrectedQuery {

    @XmlElement(name = "Keywords")
    protected String keywords;
    @XmlElement(name = "Message")
    protected String message;

    
    public String getKeywords() {
        return this.keywords;
    }

    
    public String getMessage() {
        return this.message;
    }

    
    public void setKeywords(String value) {
        this.keywords = value;
    }

    
    public void setMessage(String value) {
        this.message = value;
    }

}
