//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "source" , "content" , "isLinkSuppressed"
})
@XmlRootElement(name = "EditorialReview")
public class EditorialReview {

    @XmlElement(name = "Content")
    protected String content;
    @XmlElement(name = "IsLinkSuppressed")
    protected Boolean isLinkSuppressed;
    @XmlElement(name = "Source")
    protected String source;

    
    public String getContent() {
        return this.content;
    }

    
    public String getSource() {
        return this.source;
    }

    
    public Boolean isIsLinkSuppressed() {
        return this.isLinkSuppressed;
    }

    
    public void setContent(String value) {
        this.content = value;
    }

    
    public void setIsLinkSuppressed(Boolean value) {
        this.isLinkSuppressed = value;
    }

    
    public void setSource(String value) {
        this.source = value;
    }

}
