//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "error"
})
@XmlRootElement(name = "Errors")
public class Errors {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "code" , "message"
    })
    public static class Error {

        @XmlElement(name = "Code" , required = true)
        protected String code;
        @XmlElement(name = "Message" , required = true)
        protected String message;

        
        public String getCode() {
            return this.code;
        }

        
        public String getMessage() {
            return this.message;
        }

        
        public void setCode(String value) {
            this.code = value;
        }

        
        public void setMessage(String value) {
            this.message = value;
        }

    }

    @XmlElement(name = "Error" , required = true)
    protected List<Errors.Error> error;

    
    public List<Errors.Error> getError() {
        if (this.error == null) this.error = new ArrayList<Errors.Error>();
        return this.error;
    }

}
