//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "swatchImage" , "smallImage" , "thumbnailImage" , "tinyImage" , "mediumImage" , "largeImage"
})
@XmlRootElement(name = "ImageSet")
public class ImageSet {

    @XmlAttribute(name = "Category")
    protected String category;
    @XmlElement(name = "LargeImage")
    protected Image largeImage;
    @XmlElement(name = "MediumImage")
    protected Image mediumImage;
    @XmlElement(name = "SmallImage")
    protected Image smallImage;
    @XmlElement(name = "SwatchImage")
    protected Image swatchImage;
    @XmlElement(name = "ThumbnailImage")
    protected Image thumbnailImage;
    @XmlElement(name = "TinyImage")
    protected Image tinyImage;

    
    public String getCategory() {
        return this.category;
    }

    
    public Image getLargeImage() {
        return this.largeImage;
    }

    
    public Image getMediumImage() {
        return this.mediumImage;
    }

    
    public Image getSmallImage() {
        return this.smallImage;
    }

    
    public Image getSwatchImage() {
        return this.swatchImage;
    }

    
    public Image getThumbnailImage() {
        return this.thumbnailImage;
    }

    
    public Image getTinyImage() {
        return this.tinyImage;
    }

    
    public void setCategory(String value) {
        this.category = value;
    }

    
    public void setLargeImage(Image value) {
        this.largeImage = value;
    }

    
    public void setMediumImage(Image value) {
        this.mediumImage = value;
    }

    
    public void setSmallImage(Image value) {
        this.smallImage = value;
    }

    
    public void setSwatchImage(Image value) {
        this.swatchImage = value;
    }

    
    public void setThumbnailImage(Image value) {
        this.thumbnailImage = value;
    }

    
    public void setTinyImage(Image value) {
        this.tinyImage = value;
    }

}
