//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Image" , propOrder = {
    "url" , "height" , "width" , "isVerified"
})
public class Image {

    @XmlElement(name = "Height" , required = true)
    protected DecimalWithUnits height;
    @XmlElement(name = "IsVerified")
    protected String isVerified;
    @XmlElement(name = "URL" , required = true)
    protected String url;
    @XmlElement(name = "Width" , required = true)
    protected DecimalWithUnits width;

    
    public DecimalWithUnits getHeight() {
        return this.height;
    }

    
    public String getIsVerified() {
        return this.isVerified;
    }

    
    public String getURL() {
        return this.url;
    }

    
    public DecimalWithUnits getWidth() {
        return this.width;
    }

    
    public void setHeight(DecimalWithUnits value) {
        this.height = value;
    }

    
    public void setIsVerified(String value) {
        this.isVerified = value;
    }

    
    public void setURL(String value) {
        this.url = value;
    }

    
    public void setWidth(DecimalWithUnits value) {
        this.width = value;
    }

}
