//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemSearchRequest" , propOrder = {
    "actor" , "artist" , "availability" , "audienceRating" , "author" , "brand" , "browseNode" , "composer" ,
    "condition" , "conductor" , "director" , "itemPage" , "keywords" , "manufacturer" , "maximumPrice" , "merchantId" ,
    "minimumPrice" , "minPercentageOff" , "musicLabel" , "orchestra" , "power" , "publisher" , "relatedItemPage" ,
    "relationshipType" , "responseGroup" , "searchIndex" , "sort" , "title" , "releaseDate" , "includeReviewsSummary" ,
    "truncateReviewsAt"
})
public class ItemSearchRequest {

    @XmlElement(name = "Actor")
    protected String actor;
    @XmlElement(name = "Artist")
    protected String artist;
    @XmlElement(name = "AudienceRating")
    protected List<String> audienceRating;
    @XmlElement(name = "Author")
    protected String author;
    @XmlElement(name = "Availability")
    protected String availability;
    @XmlElement(name = "Brand")
    protected String brand;
    @XmlElement(name = "BrowseNode")
    protected String browseNode;
    @XmlElement(name = "Composer")
    protected String composer;
    @XmlElement(name = "Condition")
    protected String condition;
    @XmlElement(name = "Conductor")
    protected String conductor;
    @XmlElement(name = "Director")
    protected String director;
    @XmlElement(name = "IncludeReviewsSummary")
    protected String includeReviewsSummary;
    @XmlElement(name = "ItemPage")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger itemPage;
    @XmlElement(name = "Keywords")
    protected String keywords;
    @XmlElement(name = "Manufacturer")
    protected String manufacturer;
    @XmlElement(name = "MaximumPrice")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maximumPrice;
    @XmlElement(name = "MerchantId")
    protected String merchantId;
    @XmlElement(name = "MinimumPrice")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minimumPrice;
    @XmlElement(name = "MinPercentageOff")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minPercentageOff;
    @XmlElement(name = "MusicLabel")
    protected String musicLabel;
    @XmlElement(name = "Orchestra")
    protected String orchestra;
    @XmlElement(name = "Power")
    protected String power;
    @XmlElement(name = "Publisher")
    protected String publisher;
    @XmlElement(name = "RelatedItemPage")
    protected String relatedItemPage;
    @XmlElement(name = "RelationshipType")
    protected List<String> relationshipType;
    @XmlElement(name = "ReleaseDate")
    protected String releaseDate;
    @XmlElement(name = "ResponseGroup")
    protected List<String> responseGroup;
    @XmlElement(name = "SearchIndex")
    protected String searchIndex;
    @XmlElement(name = "Sort")
    protected String sort;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "TruncateReviewsAt")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger truncateReviewsAt;

    
    public String getActor() {
        return this.actor;
    }

    
    public String getArtist() {
        return this.artist;
    }

    
    public List<String> getAudienceRating() {
        if (this.audienceRating == null) this.audienceRating = new ArrayList<String>();
        return this.audienceRating;
    }

    
    public String getAuthor() {
        return this.author;
    }

    
    public String getAvailability() {
        return this.availability;
    }

    
    public String getBrand() {
        return this.brand;
    }

    
    public String getBrowseNode() {
        return this.browseNode;
    }

    
    public String getComposer() {
        return this.composer;
    }

    
    public String getCondition() {
        return this.condition;
    }

    
    public String getConductor() {
        return this.conductor;
    }

    
    public String getDirector() {
        return this.director;
    }

    
    public String getIncludeReviewsSummary() {
        return this.includeReviewsSummary;
    }

    
    public BigInteger getItemPage() {
        return this.itemPage;
    }

    
    public String getKeywords() {
        return this.keywords;
    }

    
    public String getManufacturer() {
        return this.manufacturer;
    }

    
    public BigInteger getMaximumPrice() {
        return this.maximumPrice;
    }

    
    public String getMerchantId() {
        return this.merchantId;
    }

    
    public BigInteger getMinimumPrice() {
        return this.minimumPrice;
    }

    
    public BigInteger getMinPercentageOff() {
        return this.minPercentageOff;
    }

    
    public String getMusicLabel() {
        return this.musicLabel;
    }

    
    public String getOrchestra() {
        return this.orchestra;
    }

    
    public String getPower() {
        return this.power;
    }

    
    public String getPublisher() {
        return this.publisher;
    }

    
    public String getRelatedItemPage() {
        return this.relatedItemPage;
    }

    
    public List<String> getRelationshipType() {
        if (this.relationshipType == null) this.relationshipType = new ArrayList<String>();
        return this.relationshipType;
    }

    
    public String getReleaseDate() {
        return this.releaseDate;
    }

    
    public List<String> getResponseGroup() {
        if (this.responseGroup == null) this.responseGroup = new ArrayList<String>();
        return this.responseGroup;
    }

    
    public String getSearchIndex() {
        return this.searchIndex;
    }

    
    public String getSort() {
        return this.sort;
    }

    
    public String getTitle() {
        return this.title;
    }

    
    public BigInteger getTruncateReviewsAt() {
        return this.truncateReviewsAt;
    }

    
    public void setActor(String value) {
        this.actor = value;
    }

    
    public void setArtist(String value) {
        this.artist = value;
    }

    
    public void setAuthor(String value) {
        this.author = value;
    }

    
    public void setAvailability(String value) {
        this.availability = value;
    }

    
    public void setBrand(String value) {
        this.brand = value;
    }

    
    public void setBrowseNode(String value) {
        this.browseNode = value;
    }

    
    public void setComposer(String value) {
        this.composer = value;
    }

    
    public void setCondition(String value) {
        this.condition = value;
    }

    
    public void setConductor(String value) {
        this.conductor = value;
    }

    
    public void setDirector(String value) {
        this.director = value;
    }

    
    public void setIncludeReviewsSummary(String value) {
        this.includeReviewsSummary = value;
    }

    
    public void setItemPage(BigInteger value) {
        this.itemPage = value;
    }

    
    public void setKeywords(String value) {
        this.keywords = value;
    }

    
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    
    public void setMaximumPrice(BigInteger value) {
        this.maximumPrice = value;
    }

    
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    
    public void setMinimumPrice(BigInteger value) {
        this.minimumPrice = value;
    }

    
    public void setMinPercentageOff(BigInteger value) {
        this.minPercentageOff = value;
    }

    
    public void setMusicLabel(String value) {
        this.musicLabel = value;
    }

    
    public void setOrchestra(String value) {
        this.orchestra = value;
    }

    
    public void setPower(String value) {
        this.power = value;
    }

    
    public void setPublisher(String value) {
        this.publisher = value;
    }

    
    public void setRelatedItemPage(String value) {
        this.relatedItemPage = value;
    }

    
    public void setReleaseDate(String value) {
        this.releaseDate = value;
    }

    
    public void setSearchIndex(String value) {
        this.searchIndex = value;
    }

    
    public void setSort(String value) {
        this.sort = value;
    }

    
    public void setTitle(String value) {
        this.title = value;
    }

    
    public void setTruncateReviewsAt(BigInteger value) {
        this.truncateReviewsAt = value;
    }

}
