//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemLookupRequest" , propOrder = {
    "condition" , "idType" , "merchantId" , "itemId" , "responseGroup" , "searchIndex" , "variationPage" ,
    "relatedItemPage" , "relationshipType" , "includeReviewsSummary" , "truncateReviewsAt"
})
public class ItemLookupRequest {

    @XmlElement(name = "Condition")
    protected String condition;
    @XmlElement(name = "IdType")
    protected String idType;
    @XmlElement(name = "IncludeReviewsSummary")
    protected String includeReviewsSummary;
    @XmlElement(name = "ItemId")
    protected List<String> itemId;
    @XmlElement(name = "MerchantId")
    protected String merchantId;
    @XmlElement(name = "RelatedItemPage")
    protected String relatedItemPage;
    @XmlElement(name = "RelationshipType")
    protected List<String> relationshipType;
    @XmlElement(name = "ResponseGroup")
    protected List<String> responseGroup;
    @XmlElement(name = "SearchIndex")
    protected String searchIndex;
    @XmlElement(name = "TruncateReviewsAt")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger truncateReviewsAt;
    @XmlElement(name = "VariationPage")
    protected String variationPage;

    
    public String getCondition() {
        return this.condition;
    }

    
    public String getIdType() {
        return this.idType;
    }

    
    public String getIncludeReviewsSummary() {
        return this.includeReviewsSummary;
    }

    
    public List<String> getItemId() {
        if (this.itemId == null) this.itemId = new ArrayList<String>();
        return this.itemId;
    }

    
    public String getMerchantId() {
        return this.merchantId;
    }

    
    public String getRelatedItemPage() {
        return this.relatedItemPage;
    }

    
    public List<String> getRelationshipType() {
        if (this.relationshipType == null) this.relationshipType = new ArrayList<String>();
        return this.relationshipType;
    }

    
    public List<String> getResponseGroup() {
        if (this.responseGroup == null) this.responseGroup = new ArrayList<String>();
        return this.responseGroup;
    }

    
    public String getSearchIndex() {
        return this.searchIndex;
    }

    
    public BigInteger getTruncateReviewsAt() {
        return this.truncateReviewsAt;
    }

    
    public String getVariationPage() {
        return this.variationPage;
    }

    
    public void setCondition(String value) {
        this.condition = value;
    }

    
    public void setIdType(String value) {
        this.idType = value;
    }

    
    public void setIncludeReviewsSummary(String value) {
        this.includeReviewsSummary = value;
    }

    
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    
    public void setRelatedItemPage(String value) {
        this.relatedItemPage = value;
    }

    
    public void setSearchIndex(String value) {
        this.searchIndex = value;
    }

    
    public void setTruncateReviewsAt(BigInteger value) {
        this.truncateReviewsAt = value;
    }

    
    public void setVariationPage(String value) {
        this.variationPage = value;
    }

}
