//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "description" , "url"
})
@XmlRootElement(name = "ItemLink")
public class ItemLink {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "URL")
    protected String url;

    
    public String getDescription() {
        return this.description;
    }

    
    public String getURL() {
        return this.url;
    }

    
    public void setDescription(String value) {
        this.description = value;
    }

    
    public void setURL(String value) {
        this.url = value;
    }

}
