//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "asin" , "parentASIN" , "errors" , "detailPageURL" , "itemLinks" , "salesRank" , "smallImage" , "mediumImage" ,
    "largeImage" , "imageSets" , "itemAttributes" , "variationAttributes" , "relatedItems" , "collections" ,
    "subjects" , "offerSummary" , "offers" , "variationSummary" , "variations" , "customerReviews" ,
    "editorialReviews" , "similarProducts" , "accessories" , "tracks" , "browseNodes" , "alternateVersions"
})
@XmlRootElement(name = "Item")
public class Item {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "alternateVersion"
    })
    public static class AlternateVersions {

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "" , propOrder = {
            "asin" , "title" , "binding"
        })
        public static class AlternateVersion {

            @XmlElement(name = "ASIN" , required = true)
            protected String asin;
            @XmlElement(name = "Binding")
            protected String binding;
            @XmlElement(name = "Title")
            protected String title;

            
            public String getASIN() {
                return this.asin;
            }

            
            public String getBinding() {
                return this.binding;
            }

            
            public String getTitle() {
                return this.title;
            }

            
            public void setASIN(String value) {
                this.asin = value;
            }

            
            public void setBinding(String value) {
                this.binding = value;
            }

            
            public void setTitle(String value) {
                this.title = value;
            }

        }

        @XmlElement(name = "AlternateVersion")
        protected List<Item.AlternateVersions.AlternateVersion> alternateVersion;

        
        public List<Item.AlternateVersions.AlternateVersion> getAlternateVersion() {
            if (this.alternateVersion == null) this.alternateVersion =
                new ArrayList<Item.AlternateVersions.AlternateVersion>();
            return this.alternateVersion;
        }

    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "imageSet"
    })
    public static class ImageSets {

        @XmlElement(name = "ImageSet")
        protected List<ImageSet> imageSet;

        
        public List<ImageSet> getImageSet() {
            if (this.imageSet == null) this.imageSet = new ArrayList<ImageSet>();
            return this.imageSet;
        }

    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "subject"
    })
    public static class Subjects {

        @XmlElement(name = "Subject")
        protected List<String> subject;

        
        public List<String> getSubject() {
            if (this.subject == null) this.subject = new ArrayList<String>();
            return this.subject;
        }

    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "variationAttribute"
    })
    public static class VariationAttributes {

        @XmlElement(name = "VariationAttribute")
        protected List<VariationAttribute> variationAttribute;

        
        public List<VariationAttribute> getVariationAttribute() {
            if (this.variationAttribute == null) this.variationAttribute = new ArrayList<VariationAttribute>();
            return this.variationAttribute;
        }

    }

    @XmlElement(name = "Accessories")
    protected Accessories accessories;
    @XmlElement(name = "AlternateVersions")
    protected Item.AlternateVersions alternateVersions;
    @XmlElement(name = "ASIN" , required = true)
    protected String asin;
    @XmlElement(name = "BrowseNodes")
    protected BrowseNodes browseNodes;
    @XmlElement(name = "Collections")
    protected Collections collections;
    @XmlElement(name = "CustomerReviews")
    protected CustomerReviews customerReviews;
    @XmlElement(name = "DetailPageURL")
    protected String detailPageURL;
    @XmlElement(name = "EditorialReviews")
    protected EditorialReviews editorialReviews;
    @XmlElement(name = "Errors")
    protected Errors errors;
    @XmlElement(name = "ImageSets")
    protected List<Item.ImageSets> imageSets;
    @XmlElement(name = "ItemAttributes")
    protected ItemAttributes itemAttributes;
    @XmlElement(name = "ItemLinks")
    protected ItemLinks itemLinks;
    @XmlElement(name = "LargeImage")
    protected Image largeImage;
    @XmlElement(name = "MediumImage")
    protected Image mediumImage;
    @XmlElement(name = "Offers")
    protected Offers offers;
    @XmlElement(name = "OfferSummary")
    protected OfferSummary offerSummary;
    @XmlElement(name = "ParentASIN")
    protected String parentASIN;
    @XmlElement(name = "RelatedItems")
    protected List<RelatedItems> relatedItems;
    @XmlElement(name = "SalesRank")
    protected String salesRank;
    @XmlElement(name = "SimilarProducts")
    protected SimilarProducts similarProducts;
    @XmlElement(name = "SmallImage")
    protected Image smallImage;
    @XmlElement(name = "Subjects")
    protected Item.Subjects subjects;

    @XmlElement(name = "Tracks")
    protected Tracks tracks;

    @XmlElement(name = "VariationAttributes")
    protected Item.VariationAttributes variationAttributes;

    @XmlElement(name = "Variations")
    protected Variations variations;

    @XmlElement(name = "VariationSummary")
    protected VariationSummary variationSummary;

    
    public Accessories getAccessories() {
        return this.accessories;
    }

    
    public Item.AlternateVersions getAlternateVersions() {
        return this.alternateVersions;
    }

    
    public String getASIN() {
        return this.asin;
    }

    
    public BrowseNodes getBrowseNodes() {
        return this.browseNodes;
    }

    
    public Collections getCollections() {
        return this.collections;
    }

    
    public CustomerReviews getCustomerReviews() {
        return this.customerReviews;
    }

    
    public String getDetailPageURL() {
        return this.detailPageURL;
    }

    
    public EditorialReviews getEditorialReviews() {
        return this.editorialReviews;
    }

    
    public Errors getErrors() {
        return this.errors;
    }

    
    public List<Item.ImageSets> getImageSets() {
        if (this.imageSets == null) this.imageSets = new ArrayList<Item.ImageSets>();
        return this.imageSets;
    }

    
    public ItemAttributes getItemAttributes() {
        return this.itemAttributes;
    }

    
    public ItemLinks getItemLinks() {
        return this.itemLinks;
    }

    
    public Image getLargeImage() {
        return this.largeImage;
    }

    
    public Image getMediumImage() {
        return this.mediumImage;
    }

    
    public Offers getOffers() {
        return this.offers;
    }

    
    public OfferSummary getOfferSummary() {
        return this.offerSummary;
    }

    
    public String getParentASIN() {
        return this.parentASIN;
    }

    
    public List<RelatedItems> getRelatedItems() {
        if (this.relatedItems == null) this.relatedItems = new ArrayList<RelatedItems>();
        return this.relatedItems;
    }

    
    public String getSalesRank() {
        return this.salesRank;
    }

    
    public SimilarProducts getSimilarProducts() {
        return this.similarProducts;
    }

    
    public Image getSmallImage() {
        return this.smallImage;
    }

    
    public Item.Subjects getSubjects() {
        return this.subjects;
    }

    
    public Tracks getTracks() {
        return this.tracks;
    }

    
    public Item.VariationAttributes getVariationAttributes() {
        return this.variationAttributes;
    }

    
    public Variations getVariations() {
        return this.variations;
    }

    
    public VariationSummary getVariationSummary() {
        return this.variationSummary;
    }

    
    public void setAccessories(Accessories value) {
        this.accessories = value;
    }

    
    public void setAlternateVersions(Item.AlternateVersions value) {
        this.alternateVersions = value;
    }

    
    public void setASIN(String value) {
        this.asin = value;
    }

    
    public void setBrowseNodes(BrowseNodes value) {
        this.browseNodes = value;
    }

    
    public void setCollections(Collections value) {
        this.collections = value;
    }

    
    public void setCustomerReviews(CustomerReviews value) {
        this.customerReviews = value;
    }

    
    public void setDetailPageURL(String value) {
        this.detailPageURL = value;
    }

    
    public void setEditorialReviews(EditorialReviews value) {
        this.editorialReviews = value;
    }

    
    public void setErrors(Errors value) {
        this.errors = value;
    }

    
    public void setItemAttributes(ItemAttributes value) {
        this.itemAttributes = value;
    }

    
    public void setItemLinks(ItemLinks value) {
        this.itemLinks = value;
    }

    
    public void setLargeImage(Image value) {
        this.largeImage = value;
    }

    
    public void setMediumImage(Image value) {
        this.mediumImage = value;
    }

    
    public void setOffers(Offers value) {
        this.offers = value;
    }

    
    public void setOfferSummary(OfferSummary value) {
        this.offerSummary = value;
    }

    
    public void setParentASIN(String value) {
        this.parentASIN = value;
    }

    
    public void setSalesRank(String value) {
        this.salesRank = value;
    }

    
    public void setSimilarProducts(SimilarProducts value) {
        this.similarProducts = value;
    }

    
    public void setSmallImage(Image value) {
        this.smallImage = value;
    }

    
    public void setSubjects(Item.Subjects value) {
        this.subjects = value;
    }

    
    public void setTracks(Tracks value) {
        this.tracks = value;
    }

    
    public void setVariationAttributes(Item.VariationAttributes value) {
        this.variationAttributes = value;
    }

    
    public void setVariations(Variations value) {
        this.variations = value;
    }

    
    public void setVariationSummary(VariationSummary value) {
        this.variationSummary = value;
    }

}
