//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "request" , "correctedQuery" , "qid" , "engineQuery" , "totalResults" , "totalPages" , "moreSearchResultsUrl" ,
    "searchResultsMap" , "item" , "searchBinSets"
})
@XmlRootElement(name = "Items")
public class Items {

    @XmlElement(name = "CorrectedQuery")
    protected CorrectedQuery correctedQuery;
    @XmlElement(name = "EngineQuery")
    protected String engineQuery;
    @XmlElement(name = "Item")
    protected List<Item> item;
    @XmlElement(name = "MoreSearchResultsUrl")
    protected String moreSearchResultsUrl;
    @XmlElement(name = "Qid")
    protected String qid;
    @XmlElement(name = "Request")
    protected Request request;
    @XmlElement(name = "SearchBinSets")
    protected SearchBinSets searchBinSets;
    @XmlElement(name = "SearchResultsMap")
    protected SearchResultsMap searchResultsMap;
    @XmlElement(name = "TotalPages")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalPages;
    @XmlElement(name = "TotalResults")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalResults;

    
    public CorrectedQuery getCorrectedQuery() {
        return this.correctedQuery;
    }

    
    public String getEngineQuery() {
        return this.engineQuery;
    }

    
    public List<Item> getItem() {
        if (this.item == null) this.item = new ArrayList<Item>();
        return this.item;
    }

    
    public String getMoreSearchResultsUrl() {
        return this.moreSearchResultsUrl;
    }

    
    public String getQid() {
        return this.qid;
    }

    
    public Request getRequest() {
        return this.request;
    }

    
    public SearchBinSets getSearchBinSets() {
        return this.searchBinSets;
    }

    
    public SearchResultsMap getSearchResultsMap() {
        return this.searchResultsMap;
    }

    
    public BigInteger getTotalPages() {
        return this.totalPages;
    }

    
    public BigInteger getTotalResults() {
        return this.totalResults;
    }

    
    public void setCorrectedQuery(CorrectedQuery value) {
        this.correctedQuery = value;
    }

    
    public void setEngineQuery(String value) {
        this.engineQuery = value;
    }

    
    public void setMoreSearchResultsUrl(String value) {
        this.moreSearchResultsUrl = value;
    }

    
    public void setQid(String value) {
        this.qid = value;
    }

    
    public void setRequest(Request value) {
        this.request = value;
    }

    
    public void setSearchBinSets(SearchBinSets value) {
        this.searchBinSets = value;
    }

    
    public void setSearchResultsMap(SearchResultsMap value) {
        this.searchResultsMap = value;
    }

    
    public void setTotalPages(BigInteger value) {
        this.totalPages = value;
    }

    
    public void setTotalResults(BigInteger value) {
        this.totalResults = value;
    }

}
