//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "operationRequest" , "items"
})
@XmlRootElement(name = "ItemSearchResponse")
public class ItemSearchResponse {

    @XmlElement(name = "Items")
    protected List<Items> items;
    @XmlElement(name = "OperationRequest")
    protected OperationRequest operationRequest;

    
    public List<Items> getItems() {
        if (this.items == null) this.items = new ArrayList<Items>();
        return this.items;
    }

    
    public OperationRequest getOperationRequest() {
        return this.operationRequest;
    }

    
    public void setOperationRequest(OperationRequest value) {
        this.operationRequest = value;
    }

}
