//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonNegativeIntegerWithUnits" , propOrder = {
    "value"
})
public class NonNegativeIntegerWithUnits {

    @XmlAttribute(name = "Units" , required = true)
    protected String units;
    @XmlValue
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger value;

    
    public String getUnits() {
        return this.units;
    }

    
    public BigInteger getValue() {
        return this.value;
    }

    
    public void setUnits(String value) {
        this.units = value;
    }

    
    public void setValue(BigInteger value) {
        this.value = value;
    }

}
