//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


@XmlRegistry
public class ObjectFactory {

    private final static QName _AudienceRating_QNAME = new QName(
        "http://webservices.amazon.com/AWSECommerceService/2011-08-01" , "AudienceRating");
    private final static QName _Condition_QNAME = new QName(
        "http://webservices.amazon.com/AWSECommerceService/2011-08-01" , "Condition");

    
    public ObjectFactory() {
    }

    
    public Accessories createAccessories() {
        return new Accessories();
    }

    
    public Accessories.Accessory createAccessoriesAccessory() {
        return new Accessories.Accessory();
    }

    
    public Arguments createArguments() {
        return new Arguments();
    }

    
    public Arguments.Argument createArgumentsArgument() {
        return new Arguments.Argument();
    }

    
    @XmlElementDecl(namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01" ,
        name = "AudienceRating")
    public JAXBElement<String> createAudienceRating(String value) {
        return new JAXBElement<String>(ObjectFactory._AudienceRating_QNAME , String.class , null , value);
    }

    
    public Bin createBin() {
        return new Bin();
    }

    
    public Bin.BinParameter createBinBinParameter() {
        return new Bin.BinParameter();
    }

    
    public BrowseNode createBrowseNode() {
        return new BrowseNode();
    }

    
    public BrowseNode.Ancestors createBrowseNodeAncestors() {
        return new BrowseNode.Ancestors();
    }

    
    public BrowseNode.Children createBrowseNodeChildren() {
        return new BrowseNode.Children();
    }

    
    public BrowseNodeLookup createBrowseNodeLookup() {
        return new BrowseNodeLookup();
    }

    
    public BrowseNodeLookupRequest createBrowseNodeLookupRequest() {
        return new BrowseNodeLookupRequest();
    }

    
    public BrowseNodeLookupResponse createBrowseNodeLookupResponse() {
        return new BrowseNodeLookupResponse();
    }

    
    public BrowseNode.Properties createBrowseNodeProperties() {
        return new BrowseNode.Properties();
    }

    
    public BrowseNodes createBrowseNodes() {
        return new BrowseNodes();
    }

    
    public Cart createCart() {
        return new Cart();
    }

    
    public CartAdd createCartAdd() {
        return new CartAdd();
    }

    
    public CartAddRequest createCartAddRequest() {
        return new CartAddRequest();
    }

    
    public CartAddRequest.Items createCartAddRequestItems() {
        return new CartAddRequest.Items();
    }

    
    public CartAddRequest.Items.Item createCartAddRequestItemsItem() {
        return new CartAddRequest.Items.Item();
    }

    
    public CartAddResponse createCartAddResponse() {
        return new CartAddResponse();
    }

    
    public CartClear createCartClear() {
        return new CartClear();
    }

    
    public CartClearRequest createCartClearRequest() {
        return new CartClearRequest();
    }

    
    public CartClearResponse createCartClearResponse() {
        return new CartClearResponse();
    }

    
    public CartCreate createCartCreate() {
        return new CartCreate();
    }

    
    public CartCreateRequest createCartCreateRequest() {
        return new CartCreateRequest();
    }

    
    public CartCreateRequest.Items createCartCreateRequestItems() {
        return new CartCreateRequest.Items();
    }

    
    public CartCreateRequest.Items.Item createCartCreateRequestItemsItem() {
        return new CartCreateRequest.Items.Item();
    }

    
    public CartCreateRequest.Items.Item.MetaData createCartCreateRequestItemsItemMetaData() {
        return new CartCreateRequest.Items.Item.MetaData();
    }

    
    public CartCreateResponse createCartCreateResponse() {
        return new CartCreateResponse();
    }

    
    public CartGet createCartGet() {
        return new CartGet();
    }

    
    public CartGetRequest createCartGetRequest() {
        return new CartGetRequest();
    }

    
    public CartGetResponse createCartGetResponse() {
        return new CartGetResponse();
    }

    
    public CartItem createCartItem() {
        return new CartItem();
    }

    
    public CartItem.MetaData createCartItemMetaData() {
        return new CartItem.MetaData();
    }

    
    public CartItem.MetaData.KeyValuePair createCartItemMetaDataKeyValuePair() {
        return new CartItem.MetaData.KeyValuePair();
    }

    
    public CartItems createCartItems() {
        return new CartItems();
    }

    
    public CartModify createCartModify() {
        return new CartModify();
    }

    
    public CartModifyRequest createCartModifyRequest() {
        return new CartModifyRequest();
    }

    
    public CartModifyRequest.Items createCartModifyRequestItems() {
        return new CartModifyRequest.Items();
    }

    
    public CartModifyRequest.Items.Item createCartModifyRequestItemsItem() {
        return new CartModifyRequest.Items.Item();
    }

    
    public CartModifyResponse createCartModifyResponse() {
        return new CartModifyResponse();
    }

    
    public Collections createCollections() {
        return new Collections();
    }

    
    public Collections.Collection createCollectionsCollection() {
        return new Collections.Collection();
    }

    
    public Collections.Collection.CollectionItem createCollectionsCollectionCollectionItem() {
        return new Collections.Collection.CollectionItem();
    }

    
    public Collections.Collection.CollectionParent createCollectionsCollectionCollectionParent() {
        return new Collections.Collection.CollectionParent();
    }

    
    public Collections.Collection.CollectionSummary createCollectionsCollectionCollectionSummary() {
        return new Collections.Collection.CollectionSummary();
    }

    
    @XmlElementDecl(namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01" , name = "Condition")
    public JAXBElement<String> createCondition(String value) {
        return new JAXBElement<String>(ObjectFactory._Condition_QNAME , String.class , null , value);
    }

    
    public CorrectedQuery createCorrectedQuery() {
        return new CorrectedQuery();
    }

    
    public CustomerReviews createCustomerReviews() {
        return new CustomerReviews();
    }

    
    public DecimalWithUnits createDecimalWithUnits() {
        return new DecimalWithUnits();
    }

    
    public EditorialReview createEditorialReview() {
        return new EditorialReview();
    }

    
    public EditorialReviews createEditorialReviews() {
        return new EditorialReviews();
    }

    
    public Errors createErrors() {
        return new Errors();
    }

    
    public Errors.Error createErrorsError() {
        return new Errors.Error();
    }

    
    public HTTPHeaders createHTTPHeaders() {
        return new HTTPHeaders();
    }

    
    public HTTPHeaders.Header createHTTPHeadersHeader() {
        return new HTTPHeaders.Header();
    }

    
    public Image createImage() {
        return new Image();
    }

    
    public ImageSet createImageSet() {
        return new ImageSet();
    }

    
    public restful2.Item createItem() {
        return new restful2.Item();
    }

    
    public restful2.Item.AlternateVersions createItemAlternateVersions() {
        return new restful2.Item.AlternateVersions();
    }

    
    public restful2.Item.AlternateVersions.AlternateVersion createItemAlternateVersionsAlternateVersion() {
        return new restful2.Item.AlternateVersions.AlternateVersion();
    }

    
    public ItemAttributes createItemAttributes() {
        return new ItemAttributes();
    }

    
    public ItemAttributes.CatalogNumberList createItemAttributesCatalogNumberList() {
        return new ItemAttributes.CatalogNumberList();
    }

    
    public ItemAttributes.Creator createItemAttributesCreator() {
        return new ItemAttributes.Creator();
    }

    
    public ItemAttributes.EANList createItemAttributesEANList() {
        return new ItemAttributes.EANList();
    }

    
    public ItemAttributes.ItemDimensions createItemAttributesItemDimensions() {
        return new ItemAttributes.ItemDimensions();
    }

    
    public ItemAttributes.Languages createItemAttributesLanguages() {
        return new ItemAttributes.Languages();
    }

    
    public ItemAttributes.Languages.Language createItemAttributesLanguagesLanguage() {
        return new ItemAttributes.Languages.Language();
    }

    
    public ItemAttributes.PackageDimensions createItemAttributesPackageDimensions() {
        return new ItemAttributes.PackageDimensions();
    }

    
    public ItemAttributes.UPCList createItemAttributesUPCList() {
        return new ItemAttributes.UPCList();
    }

    
    public restful2.Item.ImageSets createItemImageSets() {
        return new restful2.Item.ImageSets();
    }

    
    public ItemLink createItemLink() {
        return new ItemLink();
    }

    
    public ItemLinks createItemLinks() {
        return new ItemLinks();
    }

    
    public ItemLookup createItemLookup() {
        return new ItemLookup();
    }

    
    public ItemLookupRequest createItemLookupRequest() {
        return new ItemLookupRequest();
    }

    
    public ItemLookupResponse createItemLookupResponse() {
        return new ItemLookupResponse();
    }

    
    public restful2.Items createItems() {
        return new restful2.Items();
    }

    
    public ItemSearch createItemSearch() {
        return new ItemSearch();
    }

    
    public ItemSearchRequest createItemSearchRequest() {
        return new ItemSearchRequest();
    }

    
    public ItemSearchResponse createItemSearchResponse() {
        return new ItemSearchResponse();
    }

    
    public restful2.Item.Subjects createItemSubjects() {
        return new restful2.Item.Subjects();
    }

    
    public restful2.Item.VariationAttributes createItemVariationAttributes() {
        return new restful2.Item.VariationAttributes();
    }

    
    public LoyaltyPoints createLoyaltyPoints() {
        return new LoyaltyPoints();
    }

    
    public Merchant createMerchant() {
        return new Merchant();
    }

    
    public NewReleases createNewReleases() {
        return new NewReleases();
    }

    
    public NewReleases.NewRelease createNewReleasesNewRelease() {
        return new NewReleases.NewRelease();
    }

    
    public NonNegativeIntegerWithUnits createNonNegativeIntegerWithUnits() {
        return new NonNegativeIntegerWithUnits();
    }

    
    public Offer createOffer() {
        return new Offer();
    }

    
    public OfferAttributes createOfferAttributes() {
        return new OfferAttributes();
    }

    
    public OfferListing createOfferListing() {
        return new OfferListing();
    }

    
    public OfferListing.AvailabilityAttributes createOfferListingAvailabilityAttributes() {
        return new OfferListing.AvailabilityAttributes();
    }

    
    public Offers createOffers() {
        return new Offers();
    }

    
    public OfferSummary createOfferSummary() {
        return new OfferSummary();
    }

    
    public OperationRequest createOperationRequest() {
        return new OperationRequest();
    }

    
    public OtherCategoriesSimilarProducts createOtherCategoriesSimilarProducts() {
        return new OtherCategoriesSimilarProducts();
    }

    
    public OtherCategoriesSimilarProducts.OtherCategoriesSimilarProduct
        createOtherCategoriesSimilarProductsOtherCategoriesSimilarProduct() {
        return new OtherCategoriesSimilarProducts.OtherCategoriesSimilarProduct();
    }

    
    public Price createPrice() {
        return new Price();
    }

    
    public Promotion createPromotion() {
        return new Promotion();
    }

    
    public Promotions createPromotions() {
        return new Promotions();
    }

    
    public Promotion.Summary createPromotionSummary() {
        return new Promotion.Summary();
    }

    
    public Property createProperty() {
        return new Property();
    }

    
    public RelatedItem createRelatedItem() {
        return new RelatedItem();
    }

    
    public RelatedItems createRelatedItems() {
        return new RelatedItems();
    }

    
    public Request createRequest() {
        return new Request();
    }

    
    public SavedForLaterItems createSavedForLaterItems() {
        return new SavedForLaterItems();
    }

    
    public SearchBinSet createSearchBinSet() {
        return new SearchBinSet();
    }

    
    public SearchBinSets createSearchBinSets() {
        return new SearchBinSets();
    }

    
    public SearchResultsMap createSearchResultsMap() {
        return new SearchResultsMap();
    }

    
    public SearchResultsMap.SearchIndex createSearchResultsMapSearchIndex() {
        return new SearchResultsMap.SearchIndex();
    }

    
    public SimilarityLookup createSimilarityLookup() {
        return new SimilarityLookup();
    }

    
    public SimilarityLookupRequest createSimilarityLookupRequest() {
        return new SimilarityLookupRequest();
    }

    
    public SimilarityLookupResponse createSimilarityLookupResponse() {
        return new SimilarityLookupResponse();
    }

    
    public SimilarProducts createSimilarProducts() {
        return new SimilarProducts();
    }

    
    public SimilarProducts.SimilarProduct createSimilarProductsSimilarProduct() {
        return new SimilarProducts.SimilarProduct();
    }

    
    public SimilarViewedProducts createSimilarViewedProducts() {
        return new SimilarViewedProducts();
    }

    
    public SimilarViewedProducts.SimilarViewedProduct createSimilarViewedProductsSimilarViewedProduct() {
        return new SimilarViewedProducts.SimilarViewedProduct();
    }

    
    public StringWithUnits createStringWithUnits() {
        return new StringWithUnits();
    }

    
    public TopItemSet createTopItemSet() {
        return new TopItemSet();
    }

    
    public TopItemSet.TopItem createTopItemSetTopItem() {
        return new TopItemSet.TopItem();
    }

    
    public TopSellers createTopSellers() {
        return new TopSellers();
    }

    
    public TopSellers.TopSeller createTopSellersTopSeller() {
        return new TopSellers.TopSeller();
    }

    
    public Tracks createTracks() {
        return new Tracks();
    }

    
    public Tracks.Disc createTracksDisc() {
        return new Tracks.Disc();
    }

    
    public Tracks.Disc.Track createTracksDiscTrack() {
        return new Tracks.Disc.Track();
    }

    
    public VariationAttribute createVariationAttribute() {
        return new VariationAttribute();
    }

    
    public VariationDimensions createVariationDimensions() {
        return new VariationDimensions();
    }

    
    public Variations createVariations() {
        return new Variations();
    }

    
    public VariationSummary createVariationSummary() {
        return new VariationSummary();
    }

}
