//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "offerListingId" , "price" , "salePrice" , "amountSaved" , "percentageSaved" , "availability" ,
    "availabilityAttributes" , "isEligibleForSuperSaverShipping" , "isEligibleForPrime"
})
@XmlRootElement(name = "OfferListing")
public class OfferListing {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "availabilityType" , "isPreorder" , "minimumHours" , "maximumHours"
    })
    public static class AvailabilityAttributes {

        @XmlElement(name = "AvailabilityType")
        protected String availabilityType;
        @XmlElement(name = "IsPreorder")
        protected Boolean isPreorder;
        @XmlElement(name = "MaximumHours")
        protected BigInteger maximumHours;
        @XmlElement(name = "MinimumHours")
        protected BigInteger minimumHours;

        
        public String getAvailabilityType() {
            return this.availabilityType;
        }

        
        public BigInteger getMaximumHours() {
            return this.maximumHours;
        }

        
        public BigInteger getMinimumHours() {
            return this.minimumHours;
        }

        
        public Boolean isIsPreorder() {
            return this.isPreorder;
        }

        
        public void setAvailabilityType(String value) {
            this.availabilityType = value;
        }

        
        public void setIsPreorder(Boolean value) {
            this.isPreorder = value;
        }

        
        public void setMaximumHours(BigInteger value) {
            this.maximumHours = value;
        }

        
        public void setMinimumHours(BigInteger value) {
            this.minimumHours = value;
        }

    }

    @XmlElement(name = "AmountSaved")
    protected Price amountSaved;
    @XmlElement(name = "Availability")
    protected String availability;
    @XmlElement(name = "AvailabilityAttributes")
    protected OfferListing.AvailabilityAttributes availabilityAttributes;
    @XmlElement(name = "IsEligibleForPrime")
    protected Boolean isEligibleForPrime;
    @XmlElement(name = "IsEligibleForSuperSaverShipping")
    protected Boolean isEligibleForSuperSaverShipping;
    @XmlElement(name = "OfferListingId")
    protected String offerListingId;
    @XmlElement(name = "PercentageSaved")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger percentageSaved;
    @XmlElement(name = "Price")
    protected Price price;

    @XmlElement(name = "SalePrice")
    protected Price salePrice;

    
    public Price getAmountSaved() {
        return this.amountSaved;
    }

    
    public String getAvailability() {
        return this.availability;
    }

    
    public OfferListing.AvailabilityAttributes getAvailabilityAttributes() {
        return this.availabilityAttributes;
    }

    
    public String getOfferListingId() {
        return this.offerListingId;
    }

    
    public BigInteger getPercentageSaved() {
        return this.percentageSaved;
    }

    
    public Price getPrice() {
        return this.price;
    }

    
    public Price getSalePrice() {
        return this.salePrice;
    }

    
    public Boolean isIsEligibleForPrime() {
        return this.isEligibleForPrime;
    }

    
    public Boolean isIsEligibleForSuperSaverShipping() {
        return this.isEligibleForSuperSaverShipping;
    }

    
    public void setAmountSaved(Price value) {
        this.amountSaved = value;
    }

    
    public void setAvailability(String value) {
        this.availability = value;
    }

    
    public void setAvailabilityAttributes(OfferListing.AvailabilityAttributes value) {
        this.availabilityAttributes = value;
    }

    
    public void setIsEligibleForPrime(Boolean value) {
        this.isEligibleForPrime = value;
    }

    
    public void setIsEligibleForSuperSaverShipping(Boolean value) {
        this.isEligibleForSuperSaverShipping = value;
    }

    
    public void setOfferListingId(String value) {
        this.offerListingId = value;
    }

    
    public void setPercentageSaved(BigInteger value) {
        this.percentageSaved = value;
    }

    
    public void setPrice(Price value) {
        this.price = value;
    }

    
    public void setSalePrice(Price value) {
        this.salePrice = value;
    }

}
