//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "lowestNewPrice" , "lowestUsedPrice" , "lowestCollectiblePrice" , "lowestRefurbishedPrice" , "totalNew" ,
    "totalUsed" , "totalCollectible" , "totalRefurbished"
})
@XmlRootElement(name = "OfferSummary")
public class OfferSummary {

    @XmlElement(name = "LowestCollectiblePrice")
    protected Price lowestCollectiblePrice;
    @XmlElement(name = "LowestNewPrice")
    protected Price lowestNewPrice;
    @XmlElement(name = "LowestRefurbishedPrice")
    protected Price lowestRefurbishedPrice;
    @XmlElement(name = "LowestUsedPrice")
    protected Price lowestUsedPrice;
    @XmlElement(name = "TotalCollectible")
    protected String totalCollectible;
    @XmlElement(name = "TotalNew")
    protected String totalNew;
    @XmlElement(name = "TotalRefurbished")
    protected String totalRefurbished;
    @XmlElement(name = "TotalUsed")
    protected String totalUsed;

    
    public Price getLowestCollectiblePrice() {
        return this.lowestCollectiblePrice;
    }

    
    public Price getLowestNewPrice() {
        return this.lowestNewPrice;
    }

    
    public Price getLowestRefurbishedPrice() {
        return this.lowestRefurbishedPrice;
    }

    
    public Price getLowestUsedPrice() {
        return this.lowestUsedPrice;
    }

    
    public String getTotalCollectible() {
        return this.totalCollectible;
    }

    
    public String getTotalNew() {
        return this.totalNew;
    }

    
    public String getTotalRefurbished() {
        return this.totalRefurbished;
    }

    
    public String getTotalUsed() {
        return this.totalUsed;
    }

    
    public void setLowestCollectiblePrice(Price value) {
        this.lowestCollectiblePrice = value;
    }

    
    public void setLowestNewPrice(Price value) {
        this.lowestNewPrice = value;
    }

    
    public void setLowestRefurbishedPrice(Price value) {
        this.lowestRefurbishedPrice = value;
    }

    
    public void setLowestUsedPrice(Price value) {
        this.lowestUsedPrice = value;
    }

    
    public void setTotalCollectible(String value) {
        this.totalCollectible = value;
    }

    
    public void setTotalNew(String value) {
        this.totalNew = value;
    }

    
    public void setTotalRefurbished(String value) {
        this.totalRefurbished = value;
    }

    
    public void setTotalUsed(String value) {
        this.totalUsed = value;
    }

}
