//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "merchant" , "offerAttributes" , "offerListing" , "loyaltyPoints" , "promotions"
})
@XmlRootElement(name = "Offer")
public class Offer {

    @XmlElement(name = "LoyaltyPoints")
    protected LoyaltyPoints loyaltyPoints;
    @XmlElement(name = "Merchant")
    protected Merchant merchant;
    @XmlElement(name = "OfferAttributes")
    protected OfferAttributes offerAttributes;
    @XmlElement(name = "OfferListing")
    protected List<OfferListing> offerListing;
    @XmlElement(name = "Promotions")
    protected Promotions promotions;

    
    public LoyaltyPoints getLoyaltyPoints() {
        return this.loyaltyPoints;
    }

    
    public Merchant getMerchant() {
        return this.merchant;
    }

    
    public OfferAttributes getOfferAttributes() {
        return this.offerAttributes;
    }

    
    public List<OfferListing> getOfferListing() {
        if (this.offerListing == null) this.offerListing = new ArrayList<OfferListing>();
        return this.offerListing;
    }

    
    public Promotions getPromotions() {
        return this.promotions;
    }

    
    public void setLoyaltyPoints(LoyaltyPoints value) {
        this.loyaltyPoints = value;
    }

    
    public void setMerchant(Merchant value) {
        this.merchant = value;
    }

    
    public void setOfferAttributes(OfferAttributes value) {
        this.offerAttributes = value;
    }

    
    public void setPromotions(Promotions value) {
        this.promotions = value;
    }

}
