//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "totalOffers" , "totalOfferPages" , "moreOffersUrl" , "offer"
})
@XmlRootElement(name = "Offers")
public class Offers {

    @XmlElement(name = "MoreOffersUrl")
    protected String moreOffersUrl;
    @XmlElement(name = "Offer")
    protected List<Offer> offer;
    @XmlElement(name = "TotalOfferPages")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalOfferPages;
    @XmlElement(name = "TotalOffers")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalOffers;

    
    public String getMoreOffersUrl() {
        return this.moreOffersUrl;
    }

    
    public List<Offer> getOffer() {
        if (this.offer == null) this.offer = new ArrayList<Offer>();
        return this.offer;
    }

    
    public BigInteger getTotalOfferPages() {
        return this.totalOfferPages;
    }

    
    public BigInteger getTotalOffers() {
        return this.totalOffers;
    }

    
    public void setMoreOffersUrl(String value) {
        this.moreOffersUrl = value;
    }

    
    public void setTotalOfferPages(BigInteger value) {
        this.totalOfferPages = value;
    }

    
    public void setTotalOffers(BigInteger value) {
        this.totalOffers = value;
    }

}
