//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "httpHeaders" , "requestId" , "arguments" , "errors" , "requestProcessingTime"
})
@XmlRootElement(name = "OperationRequest")
public class OperationRequest {

    @XmlElement(name = "Arguments")
    protected Arguments arguments;
    @XmlElement(name = "Errors")
    protected Errors errors;
    @XmlElement(name = "HTTPHeaders")
    protected HTTPHeaders httpHeaders;
    @XmlElement(name = "RequestId")
    protected String requestId;
    @XmlElement(name = "RequestProcessingTime")
    protected Float requestProcessingTime;

    
    public Arguments getArguments() {
        return this.arguments;
    }

    
    public Errors getErrors() {
        return this.errors;
    }

    
    public HTTPHeaders getHTTPHeaders() {
        return this.httpHeaders;
    }

    
    public String getRequestId() {
        return this.requestId;
    }

    
    public Float getRequestProcessingTime() {
        return this.requestProcessingTime;
    }

    
    public void setArguments(Arguments value) {
        this.arguments = value;
    }

    
    public void setErrors(Errors value) {
        this.errors = value;
    }

    
    public void setHTTPHeaders(HTTPHeaders value) {
        this.httpHeaders = value;
    }

    
    public void setRequestId(String value) {
        this.requestId = value;
    }

    
    public void setRequestProcessingTime(Float value) {
        this.requestProcessingTime = value;
    }

}
