//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Price" , propOrder = {
    "amount" , "currencyCode" , "formattedPrice"
})
public class Price {

    @XmlElement(name = "Amount")
    protected BigInteger amount;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "FormattedPrice" , required = true)
    protected String formattedPrice;

    
    public BigInteger getAmount() {
        return this.amount;
    }

    
    public String getCurrencyCode() {
        return this.currencyCode;
    }

    
    public String getFormattedPrice() {
        return this.formattedPrice;
    }

    
    public void setAmount(BigInteger value) {
        this.amount = value;
    }

    
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    
    public void setFormattedPrice(String value) {
        this.formattedPrice = value;
    }

}
