//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "summary"
})
@XmlRootElement(name = "Promotion")
public class Promotion {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "promotionId" , "category" , "startDate" , "endDate" , "eligibilityRequirementDescription" ,
        "benefitDescription" , "termsAndConditions"
    })
    public static class Summary {

        @XmlElement(name = "BenefitDescription")
        protected String benefitDescription;
        @XmlElement(name = "Category")
        protected String category;
        @XmlElement(name = "EligibilityRequirementDescription")
        protected String eligibilityRequirementDescription;
        @XmlElement(name = "EndDate")
        protected String endDate;
        @XmlElement(name = "PromotionId" , required = true)
        protected String promotionId;
        @XmlElement(name = "StartDate")
        protected String startDate;
        @XmlElement(name = "TermsAndConditions")
        protected String termsAndConditions;

        
        public String getBenefitDescription() {
            return this.benefitDescription;
        }

        
        public String getCategory() {
            return this.category;
        }

        
        public String getEligibilityRequirementDescription() {
            return this.eligibilityRequirementDescription;
        }

        
        public String getEndDate() {
            return this.endDate;
        }

        
        public String getPromotionId() {
            return this.promotionId;
        }

        
        public String getStartDate() {
            return this.startDate;
        }

        
        public String getTermsAndConditions() {
            return this.termsAndConditions;
        }

        
        public void setBenefitDescription(String value) {
            this.benefitDescription = value;
        }

        
        public void setCategory(String value) {
            this.category = value;
        }

        
        public void setEligibilityRequirementDescription(String value) {
            this.eligibilityRequirementDescription = value;
        }

        
        public void setEndDate(String value) {
            this.endDate = value;
        }

        
        public void setPromotionId(String value) {
            this.promotionId = value;
        }

        
        public void setStartDate(String value) {
            this.startDate = value;
        }

        
        public void setTermsAndConditions(String value) {
            this.termsAndConditions = value;
        }

    }

    @XmlElement(name = "Summary")
    protected Promotion.Summary summary;

    
    public Promotion.Summary getSummary() {
        return this.summary;
    }

    
    public void setSummary(Promotion.Summary value) {
        this.summary = value;
    }

}
