//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "relationship" , "relationshipType" , "relatedItemCount" , "relatedItemPageCount" , "relatedItemPage" ,
    "relatedItem"
})
@XmlRootElement(name = "RelatedItems")
public class RelatedItems {

    @XmlElement(name = "RelatedItem")
    protected List<RelatedItem> relatedItem;
    @XmlElement(name = "RelatedItemCount")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedItemCount;
    @XmlElement(name = "RelatedItemPage")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedItemPage;
    @XmlElement(name = "RelatedItemPageCount")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedItemPageCount;
    @XmlElement(name = "Relationship")
    protected String relationship;
    @XmlElement(name = "RelationshipType")
    protected String relationshipType;

    
    public List<RelatedItem> getRelatedItem() {
        if (this.relatedItem == null) this.relatedItem = new ArrayList<RelatedItem>();
        return this.relatedItem;
    }

    
    public BigInteger getRelatedItemCount() {
        return this.relatedItemCount;
    }

    
    public BigInteger getRelatedItemPage() {
        return this.relatedItemPage;
    }

    
    public BigInteger getRelatedItemPageCount() {
        return this.relatedItemPageCount;
    }

    
    public String getRelationship() {
        return this.relationship;
    }

    
    public String getRelationshipType() {
        return this.relationshipType;
    }

    
    public void setRelatedItemCount(BigInteger value) {
        this.relatedItemCount = value;
    }

    
    public void setRelatedItemPage(BigInteger value) {
        this.relatedItemPage = value;
    }

    
    public void setRelatedItemPageCount(BigInteger value) {
        this.relatedItemPageCount = value;
    }

    
    public void setRelationship(String value) {
        this.relationship = value;
    }

    
    public void setRelationshipType(String value) {
        this.relationshipType = value;
    }

}
