//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "isValid" , "browseNodeLookupRequest" , "itemSearchRequest" , "itemLookupRequest" , "similarityLookupRequest" ,
    "cartGetRequest" , "cartAddRequest" , "cartCreateRequest" , "cartModifyRequest" , "cartClearRequest" , "errors"
})
@XmlRootElement(name = "Request")
public class Request {

    @XmlElement(name = "BrowseNodeLookupRequest")
    protected BrowseNodeLookupRequest browseNodeLookupRequest;
    @XmlElement(name = "CartAddRequest")
    protected CartAddRequest cartAddRequest;
    @XmlElement(name = "CartClearRequest")
    protected CartClearRequest cartClearRequest;
    @XmlElement(name = "CartCreateRequest")
    protected CartCreateRequest cartCreateRequest;
    @XmlElement(name = "CartGetRequest")
    protected CartGetRequest cartGetRequest;
    @XmlElement(name = "CartModifyRequest")
    protected CartModifyRequest cartModifyRequest;
    @XmlElement(name = "Errors")
    protected Errors errors;
    @XmlElement(name = "IsValid")
    protected String isValid;
    @XmlElement(name = "ItemLookupRequest")
    protected ItemLookupRequest itemLookupRequest;
    @XmlElement(name = "ItemSearchRequest")
    protected ItemSearchRequest itemSearchRequest;
    @XmlElement(name = "SimilarityLookupRequest")
    protected SimilarityLookupRequest similarityLookupRequest;

    
    public BrowseNodeLookupRequest getBrowseNodeLookupRequest() {
        return this.browseNodeLookupRequest;
    }

    
    public CartAddRequest getCartAddRequest() {
        return this.cartAddRequest;
    }

    
    public CartClearRequest getCartClearRequest() {
        return this.cartClearRequest;
    }

    
    public CartCreateRequest getCartCreateRequest() {
        return this.cartCreateRequest;
    }

    
    public CartGetRequest getCartGetRequest() {
        return this.cartGetRequest;
    }

    
    public CartModifyRequest getCartModifyRequest() {
        return this.cartModifyRequest;
    }

    
    public Errors getErrors() {
        return this.errors;
    }

    
    public String getIsValid() {
        return this.isValid;
    }

    
    public ItemLookupRequest getItemLookupRequest() {
        return this.itemLookupRequest;
    }

    
    public ItemSearchRequest getItemSearchRequest() {
        return this.itemSearchRequest;
    }

    
    public SimilarityLookupRequest getSimilarityLookupRequest() {
        return this.similarityLookupRequest;
    }

    
    public void setBrowseNodeLookupRequest(BrowseNodeLookupRequest value) {
        this.browseNodeLookupRequest = value;
    }

    
    public void setCartAddRequest(CartAddRequest value) {
        this.cartAddRequest = value;
    }

    
    public void setCartClearRequest(CartClearRequest value) {
        this.cartClearRequest = value;
    }

    
    public void setCartCreateRequest(CartCreateRequest value) {
        this.cartCreateRequest = value;
    }

    
    public void setCartGetRequest(CartGetRequest value) {
        this.cartGetRequest = value;
    }

    
    public void setCartModifyRequest(CartModifyRequest value) {
        this.cartModifyRequest = value;
    }

    
    public void setErrors(Errors value) {
        this.errors = value;
    }

    
    public void setIsValid(String value) {
        this.isValid = value;
    }

    
    public void setItemLookupRequest(ItemLookupRequest value) {
        this.itemLookupRequest = value;
    }

    
    public void setItemSearchRequest(ItemSearchRequest value) {
        this.itemSearchRequest = value;
    }

    
    public void setSimilarityLookupRequest(SimilarityLookupRequest value) {
        this.similarityLookupRequest = value;
    }

}
