//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "similarProduct"
})
@XmlRootElement(name = "SimilarProducts")
public class SimilarProducts {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "asin" , "title"
    })
    public static class SimilarProduct {

        @XmlElement(name = "ASIN")
        protected String asin;
        @XmlElement(name = "Title")
        protected String title;

        
        public String getASIN() {
            return this.asin;
        }

        
        public String getTitle() {
            return this.title;
        }

        
        public void setASIN(String value) {
            this.asin = value;
        }

        
        public void setTitle(String value) {
            this.title = value;
        }

    }

    @XmlElement(name = "SimilarProduct" , required = true)
    protected List<SimilarProducts.SimilarProduct> similarProduct;

    
    public List<SimilarProducts.SimilarProduct> getSimilarProduct() {
        if (this.similarProduct == null) this.similarProduct = new ArrayList<SimilarProducts.SimilarProduct>();
        return this.similarProduct;
    }

}
