//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimilarityLookupRequest" , propOrder = {
    "condition" , "itemId" , "merchantId" , "responseGroup" , "similarityType"
})
public class SimilarityLookupRequest {

    @XmlElement(name = "Condition")
    protected String condition;
    @XmlElement(name = "ItemId")
    protected List<String> itemId;
    @XmlElement(name = "MerchantId")
    protected String merchantId;
    @XmlElement(name = "ResponseGroup")
    protected List<String> responseGroup;
    @XmlElement(name = "SimilarityType")
    protected String similarityType;

    
    public String getCondition() {
        return this.condition;
    }

    
    public List<String> getItemId() {
        if (this.itemId == null) this.itemId = new ArrayList<String>();
        return this.itemId;
    }

    
    public String getMerchantId() {
        return this.merchantId;
    }

    
    public List<String> getResponseGroup() {
        if (this.responseGroup == null) this.responseGroup = new ArrayList<String>();
        return this.responseGroup;
    }

    
    public String getSimilarityType() {
        return this.similarityType;
    }

    
    public void setCondition(String value) {
        this.condition = value;
    }

    
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    
    public void setSimilarityType(String value) {
        this.similarityType = value;
    }

}
