//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "type" , "topItem"
})
@XmlRootElement(name = "TopItemSet")
public class TopItemSet {

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "" , propOrder = {
        "asin" , "title" , "detailPageURL" , "productGroup" , "author" , "artist" , "actor"
    })
    public static class TopItem {

        @XmlElement(name = "Actor")
        protected List<String> actor;
        @XmlElement(name = "Artist")
        protected List<String> artist;
        @XmlElement(name = "ASIN")
        protected String asin;
        @XmlElement(name = "Author")
        protected List<String> author;
        @XmlElement(name = "DetailPageURL")
        protected String detailPageURL;
        @XmlElement(name = "ProductGroup")
        protected String productGroup;
        @XmlElement(name = "Title")
        protected String title;

        
        public List<String> getActor() {
            if (this.actor == null) this.actor = new ArrayList<String>();
            return this.actor;
        }

        
        public List<String> getArtist() {
            if (this.artist == null) this.artist = new ArrayList<String>();
            return this.artist;
        }

        
        public String getASIN() {
            return this.asin;
        }

        
        public List<String> getAuthor() {
            if (this.author == null) this.author = new ArrayList<String>();
            return this.author;
        }

        
        public String getDetailPageURL() {
            return this.detailPageURL;
        }

        
        public String getProductGroup() {
            return this.productGroup;
        }

        
        public String getTitle() {
            return this.title;
        }

        
        public void setASIN(String value) {
            this.asin = value;
        }

        
        public void setDetailPageURL(String value) {
            this.detailPageURL = value;
        }

        
        public void setProductGroup(String value) {
            this.productGroup = value;
        }

        
        public void setTitle(String value) {
            this.title = value;
        }

    }

    @XmlElement(name = "TopItem" , required = true)
    protected List<TopItemSet.TopItem> topItem;

    @XmlElement(name = "Type")
    protected String type;

    
    public List<TopItemSet.TopItem> getTopItem() {
        if (this.topItem == null) this.topItem = new ArrayList<TopItemSet.TopItem>();
        return this.topItem;
    }

    
    public String getType() {
        return this.type;
    }

    
    public void setType(String value) {
        this.type = value;
    }

}
