//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "lowestPrice" , "highestPrice" , "lowestSalePrice" , "highestSalePrice"
})
@XmlRootElement(name = "VariationSummary")
public class VariationSummary {

    @XmlElement(name = "HighestPrice")
    protected Price highestPrice;
    @XmlElement(name = "HighestSalePrice")
    protected Price highestSalePrice;
    @XmlElement(name = "LowestPrice")
    protected Price lowestPrice;
    @XmlElement(name = "LowestSalePrice")
    protected Price lowestSalePrice;

    
    public Price getHighestPrice() {
        return this.highestPrice;
    }

    
    public Price getHighestSalePrice() {
        return this.highestSalePrice;
    }

    
    public Price getLowestPrice() {
        return this.lowestPrice;
    }

    
    public Price getLowestSalePrice() {
        return this.lowestSalePrice;
    }

    
    public void setHighestPrice(Price value) {
        this.highestPrice = value;
    }

    
    public void setHighestSalePrice(Price value) {
        this.highestSalePrice = value;
    }

    
    public void setLowestPrice(Price value) {
        this.lowestPrice = value;
    }

    
    public void setLowestSalePrice(Price value) {
        this.lowestSalePrice = value;
    }

}
