//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "totalVariations" , "totalVariationPages" , "variationDimensions" , "item"
})
@XmlRootElement(name = "Variations")
public class Variations {

    @XmlElement(name = "Item")
    protected List<Item> item;
    @XmlElement(name = "TotalVariationPages")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalVariationPages;
    @XmlElement(name = "TotalVariations")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalVariations;
    @XmlElement(name = "VariationDimensions")
    protected VariationDimensions variationDimensions;

    
    public List<Item> getItem() {
        if (this.item == null) this.item = new ArrayList<Item>();
        return this.item;
    }

    
    public BigInteger getTotalVariationPages() {
        return this.totalVariationPages;
    }

    
    public BigInteger getTotalVariations() {
        return this.totalVariations;
    }

    
    public VariationDimensions getVariationDimensions() {
        return this.variationDimensions;
    }

    
    public void setTotalVariationPages(BigInteger value) {
        this.totalVariationPages = value;
    }

    
    public void setTotalVariations(BigInteger value) {
        this.totalVariations = value;
    }

    
    public void setVariationDimensions(VariationDimensions value) {
        this.variationDimensions = value;
    }

}
