//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 06:13:14 PM CDT 
//

package restful2;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "" , propOrder = {
    "name" , "value"
})
@XmlRootElement(name = "VariationAttribute")
public class VariationAttribute {

    @XmlElement(name = "Name" , required = true)
    protected String name;
    @XmlElement(name = "Value" , required = true)
    protected List<String> value;

    
    public String getName() {
        return this.name;
    }

    
    public List<String> getValue() {
        if (this.value == null) this.value = new ArrayList<String>();
        return this.value;
    }

    
    public void setName(String value) {
        this.name = value;
    }

}
